name: 'Checkout'
description: 'Checkout a Git repo using --reference'
inputs:
  repository:
    description: |
      GitHub full repo name
      Default: GITHUB_REPOSITORY
  token:
    description: |
      A token to fetch the repository.
      Typically, you would use GITHUB_TOKEN
  common-path:
    description: |
      Common (reference) git repo path under GITHUB_WORKSPACE
      Default: ${repository}.git
  path:
    description: 'Relative path under GITHUB_WORKSPACE to place the repository'
  ref:
    description: 'The branch, tag or SHA to checkout'
  clean:
    description: 'Whether to clean working directory or not'
    default: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        REPO=${{ inputs.repository }}
        REF_DIR=${{ inputs.common-path }}
        TARGET_DIR=${{ inputs.path }}
        TARGET_REF=${{ inputs.ref }}
        CLEAN=${{ inputs.clean }}

        GITHUB_REF=${{ github.ref_name }}
        GITHUB_ACTION_PATH=${{ github.action_path }}

        REPO=${REPO:-$GITHUB_REPOSITORY}
        REF_DIR=${REF_DIR:-$REPO.git}
        TARGET_REF=${TARGET_REF:-$GITHUB_REF}
        [ ! "$TARGET_DIR" ] && CLEAN=

        CMD="$SHELL $GITHUB_ACTION_PATH/git-checkout.sh --debug --repo 'https://github.com/$REPO' --ref-dir '$REF_DIR'"
        [ "$TARGET_DIR" ] && CMD="$CMD --target-dir '$TARGET_DIR'"
        [ "$TARGET_REF" ] && CMD="$CMD --target-ref '$TARGET_REF'"
        [ "$CLEAN" == "true" ] && CMD="$CMD --clean"
        echo $CMD

        eval $CMD
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
