name: 'Checkout'
description: 'Checkout a Git repo using --reference'
inputs:
  project:
    description: 'Project (tempest or chromium).'
    default: 'tempest'
  common-path:
    description: >
      Common/reference git repo path under $GITHUB_WORKSPACE.
      Default: ${project}.git
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository.'
  ref:
    description: 'The branch, tag or SHA to checkout.'
  clean:
    description: 'Whether to clean working directory or not'
    default: true
runs:
  using: 'node20'
  main: 'index.js'
